"""Complete initial schema — all 44 tables for ROHU Contable v1.2.1

Revision ID: 0001_initial
Revises:
Create Date: 2026-03-29
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0001_initial'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ── 1. tenants ──
    op.create_table('tenants',
        sa.Column('id', sa.UUID(), nullable=False, server_default=sa.text('gen_random_uuid()')),
        sa.Column('name', sa.String(255), nullable=False),
        sa.Column('trade_name', sa.String(255)),
        sa.Column('tax_id', sa.String(20), nullable=False, unique=True),
        sa.Column('tax_id_check_digit', sa.String(1)),
        sa.Column('fiscal_regime', sa.String(50), server_default='simplified'),
        sa.Column('email', sa.String(255), nullable=False),
        sa.Column('phone', sa.String(30)),
        sa.Column('address', sa.String(500)),
        sa.Column('city', sa.String(100)),
        sa.Column('country_code', sa.String(2), server_default='CO'),
        sa.Column('plan_type', sa.String(30), server_default='starter'),
        sa.Column('max_users', sa.Integer(), server_default='5'),
        sa.Column('currency_code', sa.String(3), server_default='COP'),
        sa.Column('timezone', sa.String(50), server_default='America/Bogota'),
        sa.Column('logo_url', sa.Text()),
        sa.Column('favicon_url', sa.Text()),
        sa.Column('dian_resolution_number', sa.String(50)),
        sa.Column('dian_resolution_prefix', sa.String(10), server_default='FE'),
        sa.Column('pta_provider', sa.String(50), server_default='factus'),
        sa.Column('pta_api_key', sa.Text()),
        sa.Column('smtp_host', sa.String(255)),
        sa.Column('smtp_port', sa.Integer(), server_default='587'),
        sa.Column('smtp_user', sa.String(255)),
        sa.Column('smtp_password', sa.Text()),
        sa.Column('smtp_from_email', sa.String(255)),
        sa.Column('is_active', sa.Boolean(), server_default='true'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()')),
        sa.Column('updated_at', sa.DateTime(timezone=True)),
        sa.Column('deleted_at', sa.DateTime(timezone=True)),
        sa.Column('version', sa.Integer(), server_default='1'),
        sa.PrimaryKeyConstraint('id'),
        sa.CheckConstraint("fiscal_regime IN ('simplified','common','simple','special')", name='ck_tenant_regime'),
        sa.CheckConstraint("plan_type IN ('starter','professional','enterprise')", name='ck_tenant_plan'),
        sa.CheckConstraint('max_users > 0', name='ck_tenant_max_users'),
    )

    # ── 2. permissions (no FK) ──
    op.create_table('permissions',
        sa.Column('id', sa.UUID(), nullable=False, server_default=sa.text('gen_random_uuid()')),
        sa.Column('resource', sa.String(100), nullable=False),
        sa.Column('action', sa.String(50), nullable=False),
        sa.Column('module', sa.String(50), nullable=False),
        sa.Column('description', sa.Text()),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()')),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('resource', 'action', name='uq_perm_resource_action'),
    )

    # ── 3. users ──
    op.create_table('users',
        sa.Column('id', sa.UUID(), nullable=False, server_default=sa.text('gen_random_uuid()')),
        sa.Column('tenant_id', sa.UUID(), nullable=False),
        sa.Column('email', sa.String(255), nullable=False),
        sa.Column('password_hash', sa.String(255), nullable=False),
        sa.Column('first_name', sa.String(100), nullable=False),
        sa.Column('last_name', sa.String(100), nullable=False),
        sa.Column('phone', sa.String(30)),
        sa.Column('is_active', sa.Boolean(), server_default='true'),
        sa.Column('email_verified_at', sa.DateTime(timezone=True)),
        sa.Column('last_login_at', sa.DateTime(timezone=True)),
        sa.Column('failed_login_count', sa.Integer(), server_default='0'),
        sa.Column('locked_at', sa.DateTime(timezone=True)),
        sa.Column('must_change_password', sa.Boolean(), server_default='false'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()')),
        sa.Column('updated_at', sa.DateTime(timezone=True)),
        sa.Column('deleted_at', sa.DateTime(timezone=True)),
        sa.Column('version', sa.Integer(), server_default='1'),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('tenant_id', 'email', name='uq_user_tenant_email'),
    )
    op.create_index('ix_users_tenant_id', 'users', ['tenant_id'])

    # ── 4. roles ──
    op.create_table('roles',
        sa.Column('id', sa.UUID(), nullable=False, server_default=sa.text('gen_random_uuid()')),
        sa.Column('tenant_id', sa.UUID()),
        sa.Column('name', sa.String(100), nullable=False),
        sa.Column('description', sa.Text()),
        sa.Column('is_system_role', sa.Boolean(), server_default='false'),
        sa.Column('is_active', sa.Boolean(), server_default='true'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()')),
        sa.Column('updated_at', sa.DateTime(timezone=True)),
        sa.Column('version', sa.Integer(), server_default='1'),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('tenant_id', 'name', name='uq_role_tenant_name'),
    )

    # ── 5. role_permissions ──
    op.create_table('role_permissions',
        sa.Column('role_id', sa.UUID(), nullable=False),
        sa.Column('permission_id', sa.UUID(), nullable=False),
        sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()')),
        sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('role_id', 'permission_id'),
    )

    # ── 6. user_roles ──
    op.create_table('user_roles',
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('role_id', sa.UUID(), nullable=False),
        sa.Column('tenant_id', sa.UUID(), nullable=False),
        sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()')),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('user_id', 'role_id'),
    )

    # ── 7. refresh_tokens ──
    op.create_table('refresh_tokens',
        sa.Column('id', sa.UUID(), nullable=False, server_default=sa.text('gen_random_uuid()')),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('tenant_id', sa.UUID(), nullable=False),
        sa.Column('token_hash', sa.String(255), nullable=False, unique=True),
        sa.Column('device_name', sa.String(255)),
        sa.Column('ip_address', sa.String(45)),
        sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('is_revoked', sa.Boolean(), server_default='false'),
        sa.Column('revoked_at', sa.DateTime(timezone=True)),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()')),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )

    # ── 8. categories ──
    op.create_table('categories',
        sa.Column('id', sa.UUID(), nullable=False, server_default=sa.text('gen_random_uuid()')),
        sa.Column('tenant_id', sa.UUID(), nullable=False),
        sa.Column('parent_id', sa.UUID()),
        sa.Column('name', sa.String(255), nullable=False),
        sa.Column('tax_type', sa.String(20), server_default='iva_19'),
        sa.Column('tax_rate', sa.Numeric(8, 4), server_default='19.0'),
        sa.Column('is_active', sa.Boolean(), server_default='true'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()')),
        sa.Column('updated_at', sa.DateTime(timezone=True)),
        sa.Column('version', sa.Integer(), server_default='1'),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id']),
        sa.ForeignKeyConstraint(['parent_id'], ['categories.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('tenant_id', 'name', 'parent_id', name='uq_cat_tenant_name_parent'),
        sa.CheckConstraint("tax_type IN ('iva_19','iva_5','exempt','excluded')", name='ck_cat_tax_type'),
        sa.CheckConstraint('tax_rate >= 0 AND tax_rate <= 100', name='ck_cat_tax_rate'),
    )

    # ── 9. suppliers ──
    op.create_table('suppliers',
        sa.Column('id', sa.UUID(), nullable=False, server_default=sa.text('gen_random_uuid()')),
        sa.Column('tenant_id', sa.UUID(), nullable=False),
        sa.Column('created_by', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(255), nullable=False),
        sa.Column('tax_id', sa.String(20)),
        sa.Column('contact_name', sa.String(255)),
        sa.Column('phone', sa.String(30)),
        sa.Column('email', sa.String(255)),
        sa.Column('address', sa.String(500)),
        sa.Column('city', sa.String(100)),
        sa.Column('payment_terms_days', sa.Integer(), server_default='0'),
        sa.Column('notes', sa.Text()),
        sa.Column('is_active', sa.Boolean(), server_default='true'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()')),
        sa.Column('updated_at', sa.DateTime(timezone=True)),
        sa.Column('deleted_at', sa.DateTime(timezone=True)),
        sa.Column('version', sa.Integer(), server_default='1'),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id']),
        sa.ForeignKeyConstraint(['created_by'], ['users.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('tenant_id', 'tax_id', name='uq_supplier_tenant_taxid'),
    )
    op.create_index('ix_suppliers_tenant_name', 'suppliers', ['tenant_id', 'name'])

    # ── 10. customers ──
    op.create_table('customers',
        sa.Column('id', sa.UUID(), nullable=False, server_default=sa.text('gen_random_uuid()')),
        sa.Column('tenant_id', sa.UUID(), nullable=False),
        sa.Column('created_by', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(255), nullable=False),
        sa.Column('tax_id', sa.String(20)),
        sa.Column('tax_id_type', sa.String(10), server_default='CC'),
        sa.Column('contact_name', sa.String(255)),
        sa.Column('phone', sa.String(30)),
        sa.Column('email', sa.String(255)),
        sa.Column('address', sa.String(500)),
        sa.Column('city', sa.String(100)),
        sa.Column('credit_limit', sa.Numeric(18, 2), server_default='0'),
        sa.Column('credit_days', sa.Integer(), server_default='0'),
        sa.Column('notes', sa.Text()),
        sa.Column('is_active', sa.Boolean(), server_default='true'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()')),
        sa.Column('updated_at', sa.DateTime(timezone=True)),
        sa.Column('deleted_at', sa.DateTime(timezone=True)),
        sa.Column('version', sa.Integer(), server_default='1'),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id']),
        sa.ForeignKeyConstraint(['created_by'], ['users.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('tenant_id', 'tax_id', name='uq_customer_tenant_taxid'),
    )
    op.create_index('ix_customers_tenant_name', 'customers', ['tenant_id', 'name'])

    # ── 11. products ──
    op.create_table('products',
        sa.Column('id', sa.UUID(), nullable=False, server_default=sa.text('gen_random_uuid()')),
        sa.Column('tenant_id', sa.UUID(), nullable=False),
        sa.Column('category_id', sa.UUID()),
        sa.Column('created_by', sa.UUID(), nullable=False),
        sa.Column('sku', sa.String(50)),
        sa.Column('qr_code', sa.String(100)),
        sa.Column('barcode', sa.String(100)),
        sa.Column('name', sa.String(255), nullable=False),
        sa.Column('description', sa.Text()),
        sa.Column('unit', sa.String(20), server_default='unit'),
        sa.Column('purchase_price', sa.Numeric(18, 2), server_default='0'),
        sa.Column('sale_price', sa.Numeric(18, 2), server_default='0'),
        sa.Column('cost_average', sa.Numeric(18, 6), server_default='0'),
        sa.Column('tax_type', sa.String(20), server_default='iva_19'),
        sa.Column('tax_rate', sa.Numeric(8, 4), server_default='19.0'),
        sa.Column('stock_current', sa.Numeric(12, 4), server_default='0'),
        sa.Column('stock_minimum', sa.Numeric(12, 4), server_default='0'),
        sa.Column('is_active', sa.Boolean(), server_default='true'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()')),
        sa.Column('updated_at', sa.DateTime(timezone=True)),
        sa.Column('deleted_at', sa.DateTime(timezone=True)),
        sa.Column('version', sa.Integer(), server_default='1'),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id']),
        sa.ForeignKeyConstraint(['category_id'], ['categories.id']),
        sa.ForeignKeyConstraint(['created_by'], ['users.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('tenant_id', 'qr_code', name='uq_product_tenant_qr'),
        sa.UniqueConstraint('tenant_id', 'barcode', name='uq_product_tenant_barcode'),
        sa.UniqueConstraint('tenant_id', 'sku', name='uq_product_tenant_sku'),
        sa.CheckConstraint("unit IN ('unit','kg','g','lt','ml','box','pack','meter')", name='ck_product_unit'),
        sa.CheckConstraint("tax_type IN ('iva_19','iva_5','exempt','excluded')", name='ck_product_tax_type'),
        sa.CheckConstraint('purchase_price >= 0', name='ck_product_purchase_price'),
        sa.CheckConstraint('sale_price >= 0', name='ck_product_sale_price'),
    )
    op.create_index('ix_products_tenant_name', 'products', ['tenant_id', 'name'])
    op.create_index('ix_products_tenant_active', 'products', ['tenant_id', 'is_active'])

    # ── 12. accounting_periods ──
    op.create_table('accounting_periods',
        sa.Column('id', sa.UUID(), nullable=False, server_default=sa.text('gen_random_uuid()')),
        sa.Column('tenant_id', sa.UUID(), nullable=False),
        sa.Column('year', sa.Integer(), nullable=False),
        sa.Column('month', sa.Integer(), nullable=False),
        sa.Column('status', sa.String(20), server_default='open'),
        sa.Column('closed_at', sa.DateTime(timezone=True)),
        sa.Column('closed_by', sa.UUID()),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()')),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id']),
        sa.ForeignKeyConstraint(['closed_by'], ['users.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('tenant_id', 'year', 'month', name='uq_period_tenant_year_month'),
        sa.CheckConstraint('month >= 1 AND month <= 12', name='ck_period_month'),
        sa.CheckConstraint("status IN ('open','closed','locked')", name='ck_period_status'),
    )

    # ── 13. chart_of_accounts ──
    op.create_table('chart_of_accounts',
        sa.Column('id', sa.UUID(), nullable=False, server_default=sa.text('gen_random_uuid()')),
        sa.Column('tenant_id', sa.UUID(), nullable=False),
        sa.Column('puc_code', sa.String(10), nullable=False),
        sa.Column('name', sa.String(255), nullable=False),
        sa.Column('account_type', sa.String(20), nullable=False),
        sa.Column('normal_balance', sa.String(10), nullable=False),
        sa.Column('parent_code', sa.String(10)),
        sa.Column('is_system', sa.Boolean(), server_default='false'),
        sa.Column('is_active', sa.Boolean(), server_default='true'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()')),
        sa.Column('version', sa.Integer(), server_default='1'),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('tenant_id', 'puc_code', name='uq_coa_tenant_puc'),
        sa.CheckConstraint("account_type IN ('asset','liability','equity','income','expense','cost')", name='ck_coa_type'),
        sa.CheckConstraint("normal_balance IN ('debit','credit')", name='ck_coa_balance'),
    )
    op.create_index('ix_coa_tenant_type', 'chart_of_accounts', ['tenant_id', 'account_type'])

    # ── 14. cash_sessions ──
    op.create_table('cash_sessions',
        sa.Column('id', sa.UUID(), nullable=False, server_default=sa.text('gen_random_uuid()')),
        sa.Column('tenant_id', sa.UUID(), nullable=False),
        sa.Column('opened_by', sa.UUID(), nullable=False),
        sa.Column('closed_by', sa.UUID()),
        sa.Column('opening_amount', sa.Numeric(18, 2), server_default='0'),
        sa.Column('closing_amount', sa.Numeric(18, 2)),
        sa.Column('expected_amount', sa.Numeric(18, 2)),
        sa.Column('difference', sa.Numeric(18, 2)),
        sa.Column('status', sa.String(20), server_default='open'),
        sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.text('now()')),
        sa.Column('closed_at', sa.DateTime(timezone=True)),
        sa.Column('notes', sa.Text()),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id']),
        sa.ForeignKeyConstraint(['opened_by'], ['users.id']),
        sa.ForeignKeyConstraint(['closed_by'], ['users.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.CheckConstraint("status IN ('open','closed')", name='ck_cs_status'),
        sa.CheckConstraint('opening_amount >= 0', name='ck_cs_opening'),
    )
    op.create_index('ix_cs_tenant_status', 'cash_sessions', ['tenant_id', 'status'])

    # ── 15. sales ──
    op.create_table('sales',
        sa.Column('id', sa.UUID(), nullable=False, server_default=sa.text('gen_random_uuid()')),
        sa.Column('tenant_id', sa.UUID(), nullable=False),
        sa.Column('cash_session_id', sa.UUID()),
        sa.Column('cashier_id', sa.UUID(), nullable=False),
        sa.Column('invoice_number', sa.String(30), nullable=False),
        sa.Column('sale_date', sa.DateTime(timezone=True), server_default=sa.text('now()')),
        sa.Column('status', sa.String(20), server_default='completed'),
        sa.Column('subtotal', sa.Numeric(18, 2), server_default='0'),
        sa.Column('tax_amount', sa.Numeric(18, 2), server_default='0'),
        sa.Column('discount_amount', sa.Numeric(18, 2), server_default='0'),
        sa.Column('total_amount', sa.Numeric(18, 2), server_default='0'),
        sa.Column('customer_id', sa.UUID()),
        sa.Column('customer_name', sa.String(255)),
        sa.Column('customer_tax_id', sa.String(20)),
        sa.Column('sale_type', sa.String(20), server_default='cash'),
        sa.Column('credit_days', sa.Integer(), server_default='0'),
        sa.Column('due_date', sa.DateTime(timezone=True)),
        sa.Column('payment_status', sa.String(20), server_default='paid'),
        sa.Column('amount_paid', sa.Numeric(18, 2), server_default='0'),
        sa.Column('amount_due', sa.Numeric(18, 2), server_default='0'),
        sa.Column('notes', sa.Text()),
        sa.Column('voided_at', sa.DateTime(timezone=True)),
        sa.Column('voided_by', sa.UUID()),
        sa.Column('void_reason', sa.String(255)),
        sa.Column('idempotency_key', sa.UUID(), unique=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()')),
        sa.Column('version', sa.Integer(), server_default='1'),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id']),
        sa.ForeignKeyConstraint(['cash_session_id'], ['cash_sessions.id']),
        sa.ForeignKeyConstraint(['cashier_id'], ['users.id']),
        sa.ForeignKeyConstraint(['customer_id'], ['customers.id']),
        sa.ForeignKeyConstraint(['voided_by'], ['users.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('tenant_id', 'invoice_number', name='uq_sale_tenant_invoice'),
        sa.CheckConstraint("status IN ('completed','voided')", name='ck_sale_status'),
        sa.CheckConstraint("sale_type IN ('cash','credit')", name='ck_sale_type'),
        sa.CheckConstraint("payment_status IN ('paid','pending','partial','overdue')", name='ck_sale_pay_status'),
        sa.CheckConstraint('total_amount >= 0', name='ck_sale_total'),
    )
    op.create_index('ix_sales_tenant_date', 'sales', ['tenant_id', 'sale_date'])
    op.create_index('ix_sales_tenant_status', 'sales', ['tenant_id', 'status'])
    op.create_index('ix_sales_tenant_cashier_date', 'sales', ['tenant_id', 'cashier_id', 'sale_date'])

    # ── 16. sale_items ──
    op.create_table('sale_items',
        sa.Column('id', sa.UUID(), nullable=False, server_default=sa.text('gen_random_uuid()')),
        sa.Column('sale_id', sa.UUID(), nullable=False),
        sa.Column('product_id', sa.UUID(), nullable=False),
        sa.Column('product_name', sa.String(255), nullable=False),
        sa.Column('product_sku', sa.String(50)),
        sa.Column('quantity', sa.Numeric(12, 4), nullable=False),
        sa.Column('unit_price', sa.Numeric(18, 2), nullable=False),
        sa.Column('unit_cost', sa.Numeric(18, 6), nullable=False),
        sa.Column('tax_rate', sa.Numeric(8, 4), server_default='0'),
        sa.Column('discount_pct', sa.Numeric(8, 4), server_default='0'),
        sa.Column('subtotal', sa.Numeric(18, 2), nullable=False),
        sa.Column('tax_amount', sa.Numeric(18, 2), nullable=False),
        sa.Column('total', sa.Numeric(18, 2), nullable=False),
        sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['product_id'], ['products.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.CheckConstraint('quantity > 0', name='ck_si_qty'),
        sa.CheckConstraint('unit_price >= 0', name='ck_si_price'),
    )

    # ── 17. payments ──
    op.create_table('payments',
        sa.Column('id', sa.UUID(), nullable=False, server_default=sa.text('gen_random_uuid()')),
        sa.Column('sale_id', sa.UUID(), nullable=False),
        sa.Column('tenant_id', sa.UUID(), nullable=False),
        sa.Column('method', sa.String(30), nullable=False),
        sa.Column('amount', sa.Numeric(18, 2), nullable=False),
        sa.Column('reference', sa.String(100)),
        sa.Column('received_amount', sa.Numeric(18, 2)),
        sa.Column('change_amount', sa.Numeric(18, 2), server_default='0'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()')),
        sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.CheckConstraint("method IN ('cash','card','transfer','nequi','daviplata','mixed')", name='ck_pay_method'),
        sa.CheckConstraint('amount > 0', name='ck_pay_amount'),
    )

    # ── 18. credit_notes ──
    op.create_table('credit_notes',
        sa.Column('id', sa.UUID(), nullable=False, server_default=sa.text('gen_random_uuid()')),
        sa.Column('tenant_id', sa.UUID(), nullable=False),
        sa.Column('sale_id', sa.UUID(), nullable=False),
        sa.Column('created_by', sa.UUID(), nullable=False),
        sa.Column('credit_note_number', sa.String(30), nullable=False),
        sa.Column('reason', sa.String(255), nullable=False),
        sa.Column('subtotal', sa.Numeric(18, 2), server_default='0'),
        sa.Column('tax_amount', sa.Numeric(18, 2), server_default='0'),
        sa.Column('total_amount', sa.Numeric(18, 2), server_default='0'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()')),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id']),
        sa.ForeignKeyConstraint(['sale_id'], ['sales.id']),
        sa.ForeignKeyConstraint(['created_by'], ['users.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('tenant_id', 'credit_note_number', name='uq_cn_tenant_number'),
    )

    # ── 19. credit_note_items ──
    op.create_table('credit_note_items',
        sa.Column('id', sa.UUID(), nullable=False, server_default=sa.text('gen_random_uuid()')),
        sa.Column('credit_note_id', sa.UUID(), nullable=False),
        sa.Column('product_id', sa.UUID(), nullable=False),
        sa.Column('product_name', sa.String(255), nullable=False),
        sa.Column('quantity', sa.Numeric(12, 4), nullable=False),
        sa.Column('unit_price', sa.Numeric(18, 2), nullable=False),
        sa.Column('unit_cost', sa.Numeric(18, 6), nullable=False),
        sa.Column('tax_rate', sa.Numeric(8, 4), server_default='0'),
        sa.Column('subtotal', sa.Numeric(18, 2), nullable=False),
        sa.Column('tax_amount', sa.Numeric(18, 2), nullable=False),
        sa.Column('total', sa.Numeric(18, 2), nullable=False),
        sa.ForeignKeyConstraint(['credit_note_id'], ['credit_notes.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['product_id'], ['products.id']),
        sa.PrimaryKeyConstraint('id'),
    )

    # ── 20. customer_payments ──
    op.create_table('customer_payments',
        sa.Column('id', sa.UUID(), nullable=False, server_default=sa.text('gen_random_uuid()')),
        sa.Column('tenant_id', sa.UUID(), nullable=False),
        sa.Column('customer_id', sa.UUID(), nullable=False),
        sa.Column('sale_id', sa.UUID()),
        sa.Column('created_by', sa.UUID(), nullable=False),
        sa.Column('payment_number', sa.String(30), nullable=False),
        sa.Column('payment_date', sa.DateTime(timezone=True), server_default=sa.text('now()')),
        sa.Column('amount', sa.Numeric(18, 2), nullable=False),
        sa.Column('payment_method', sa.String(30), server_default='cash'),
        sa.Column('reference', sa.String(100)),
        sa.Column('notes', sa.Text()),
        sa.Column('status', sa.String(20), server_default='completed'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()')),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id']),
        sa.ForeignKeyConstraint(['customer_id'], ['customers.id']),
        sa.ForeignKeyConstraint(['sale_id'], ['sales.id']),
        sa.ForeignKeyConstraint(['created_by'], ['users.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('tenant_id', 'payment_number', name='uq_cpay_tenant_number'),
        sa.CheckConstraint('amount > 0', name='ck_cpay_amount'),
        sa.CheckConstraint("status IN ('completed','voided')", name='ck_cpay_status'),
    )
    op.create_index('ix_cpay_tenant_customer', 'customer_payments', ['tenant_id', 'customer_id'])

    # ── 21. sales_debit_notes ──
    op.create_table('sales_debit_notes',
        sa.Column('id', sa.UUID(), nullable=False, server_default=sa.text('gen_random_uuid()')),
        sa.Column('tenant_id', sa.UUID(), nullable=False),
        sa.Column('customer_id', sa.UUID(), nullable=False),
        sa.Column('sale_id', sa.UUID()),
        sa.Column('created_by', sa.UUID(), nullable=False),
        sa.Column('note_number', sa.String(30), nullable=False),
        sa.Column('reason', sa.String(255), nullable=False),
        sa.Column('amount', sa.Numeric(18, 2), nullable=False),
        sa.Column('tax_amount', sa.Numeric(18, 2), server_default='0'),
        sa.Column('total_amount', sa.Numeric(18, 2), nullable=False),
        sa.Column('status', sa.String(20), server_default='active'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()')),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id']),
        sa.ForeignKeyConstraint(['customer_id'], ['customers.id']),
        sa.ForeignKeyConstraint(['sale_id'], ['sales.id']),
        sa.ForeignKeyConstraint(['created_by'], ['users.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('tenant_id', 'note_number', name='uq_sdn_tenant_number'),
        sa.CheckConstraint('amount > 0', name='ck_sdn_amount'),
    )

    # ── 22. collection_campaigns ──
    op.create_table('collection_campaigns',
        sa.Column('id', sa.UUID(), nullable=False, server_default=sa.text('gen_random_uuid()')),
        sa.Column('tenant_id', sa.UUID(), nullable=False),
        sa.Column('created_by', sa.UUID(), nullable=False),
        sa.Column('campaign_number', sa.String(30), nullable=False),
        sa.Column('name', sa.String(255), nullable=False),
        sa.Column('target_type', sa.String(30), server_default='all_overdue'),
        sa.Column('min_days_overdue', sa.Integer(), server_default='0'),
        sa.Column('min_amount_due', sa.Numeric(18, 2), server_default='0'),
        sa.Column('message_template', sa.Text()),
        sa.Column('status', sa.String(20), server_default='draft'),
        sa.Column('scheduled_date', sa.DateTime(timezone=True)),
        sa.Column('executed_at', sa.DateTime(timezone=True)),
        sa.Column('total_customers', sa.Integer(), server_default='0'),
        sa.Column('total_amount_targeted', sa.Numeric(18, 2), server_default='0'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()')),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id']),
        sa.ForeignKeyConstraint(['created_by'], ['users.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('tenant_id', 'campaign_number', name='uq_cc_tenant_number'),
        sa.CheckConstraint("target_type IN ('all_overdue','by_age','by_amount','specific_customers')", name='ck_cc_target'),
        sa.CheckConstraint("status IN ('draft','active','completed','cancelled')", name='ck_cc_status'),
    )

    # ── 23. collection_campaign_items ──
    op.create_table('collection_campaign_items',
        sa.Column('id', sa.UUID(), nullable=False, server_default=sa.text('gen_random_uuid()')),
        sa.Column('campaign_id', sa.UUID(), nullable=False),
        sa.Column('customer_id', sa.UUID(), nullable=False),
        sa.Column('sale_id', sa.UUID()),
        sa.Column('amount_due', sa.Numeric(18, 2), nullable=False),
        sa.Column('days_overdue', sa.Integer(), server_default='0'),
        sa.Column('contact_method', sa.String(20), server_default='phone_call'),
        sa.Column('contact_status', sa.String(20), server_default='pending'),
        sa.Column('contact_date', sa.DateTime(timezone=True)),
        sa.Column('promise_date', sa.DateTime(timezone=True)),
        sa.Column('rendered_message', sa.Text()),
        sa.Column('notes', sa.Text()),
        sa.ForeignKeyConstraint(['campaign_id'], ['collection_campaigns.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['customer_id'], ['customers.id']),
        sa.ForeignKeyConstraint(['sale_id'], ['sales.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.CheckConstraint("contact_method IN ('sms','whatsapp','email','phone_call')", name='ck_cci_method'),
        sa.CheckConstraint("contact_status IN ('pending','contacted','promised','paid','failed')", name='ck_cci_status'),
    )

    # ── 24. purchase_orders ──
    op.create_table('purchase_orders',
        sa.Column('id', sa.UUID(), nullable=False, server_default=sa.text('gen_random_uuid()')),
        sa.Column('tenant_id', sa.UUID(), nullable=False),
        sa.Column('supplier_id', sa.UUID(), nullable=False),
        sa.Column('created_by', sa.UUID(), nullable=False),
        sa.Column('order_number', sa.String(30), nullable=False),
        sa.Column('order_date', sa.DateTime(timezone=True), server_default=sa.text('now()')),
        sa.Column('expected_date', sa.DateTime(timezone=True)),
        sa.Column('status', sa.String(20), server_default='draft'),
        sa.Column('payment_type', sa.String(20), server_default='cash'),
        sa.Column('subtotal', sa.Numeric(18, 2), server_default='0'),
        sa.Column('tax_amount', sa.Numeric(18, 2), server_default='0'),
        sa.Column('total_amount', sa.Numeric(18, 2), server_default='0'),
        sa.Column('supplier_invoice', sa.String(50)),
        sa.Column('notes', sa.Text()),
        sa.Column('received_at', sa.DateTime(timezone=True)),
        sa.Column('received_by', sa.UUID()),
        sa.Column('cancelled_at', sa.DateTime(timezone=True)),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()')),
        sa.Column('updated_at', sa.DateTime(timezone=True)),
        sa.Column('version', sa.Integer(), server_default='1'),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id']),
        sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id']),
        sa.ForeignKeyConstraint(['created_by'], ['users.id']),
        sa.ForeignKeyConstraint(['received_by'], ['users.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('tenant_id', 'order_number', name='uq_po_tenant_number'),
        sa.CheckConstraint("status IN ('draft','sent','received','partially_received','cancelled')", name='ck_po_status'),
        sa.CheckConstraint("payment_type IN ('cash','credit')", name='ck_po_payment'),
    )
    op.create_index('ix_po_tenant_status', 'purchase_orders', ['tenant_id', 'status'])
    op.create_index('ix_po_tenant_date', 'purchase_orders', ['tenant_id', 'order_date'])

    # ── 25. purchase_order_items ──
    op.create_table('purchase_order_items',
        sa.Column('id', sa.UUID(), nullable=False, server_default=sa.text('gen_random_uuid()')),
        sa.Column('order_id', sa.UUID(), nullable=False),
        sa.Column('product_id', sa.UUID(), nullable=False),
        sa.Column('product_name', sa.String(255), nullable=False),
        sa.Column('quantity_ordered', sa.Numeric(12, 4), nullable=False),
        sa.Column('quantity_received', sa.Numeric(12, 4), server_default='0'),
        sa.Column('unit_cost', sa.Numeric(18, 2), nullable=False),
        sa.Column('tax_rate', sa.Numeric(8, 4), server_default='19.0'),
        sa.Column('subtotal', sa.Numeric(18, 2), nullable=False),
        sa.Column('tax_amount', sa.Numeric(18, 2), nullable=False),
        sa.Column('total', sa.Numeric(18, 2), nullable=False),
        sa.ForeignKeyConstraint(['order_id'], ['purchase_orders.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['product_id'], ['products.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.CheckConstraint('quantity_ordered > 0', name='ck_poi_qty'),
        sa.CheckConstraint('quantity_received >= 0', name='ck_poi_recv'),
        sa.CheckConstraint('unit_cost >= 0', name='ck_poi_cost'),
    )

    # ── 26. supplier_payments ──
    op.create_table('supplier_payments',
        sa.Column('id', sa.UUID(), nullable=False, server_default=sa.text('gen_random_uuid()')),
        sa.Column('tenant_id', sa.UUID(), nullable=False),
        sa.Column('supplier_id', sa.UUID(), nullable=False),
        sa.Column('purchase_order_id', sa.UUID()),
        sa.Column('created_by', sa.UUID(), nullable=False),
        sa.Column('payment_number', sa.String(30), nullable=False),
        sa.Column('payment_date', sa.DateTime(timezone=True), server_default=sa.text('now()')),
        sa.Column('amount', sa.Numeric(18, 2), nullable=False),
        sa.Column('payment_method', sa.String(30), server_default='cash'),
        sa.Column('reference', sa.String(100)),
        sa.Column('bank_account', sa.String(50)),
        sa.Column('notes', sa.Text()),
        sa.Column('status', sa.String(20), server_default='completed'),
        sa.Column('voided_at', sa.DateTime(timezone=True)),
        sa.Column('voided_by', sa.UUID()),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()')),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id']),
        sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id']),
        sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id']),
        sa.ForeignKeyConstraint(['created_by'], ['users.id']),
        sa.ForeignKeyConstraint(['voided_by'], ['users.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('tenant_id', 'payment_number', name='uq_sp_tenant_number'),
        sa.CheckConstraint('amount > 0', name='ck_sp_amount'),
        sa.CheckConstraint("status IN ('completed','voided')", name='ck_sp_status'),
        sa.CheckConstraint("payment_method IN ('cash','transfer','check','nequi','daviplata')", name='ck_sp_method'),
    )
    op.create_index('ix_sp_tenant_supplier', 'supplier_payments', ['tenant_id', 'supplier_id'])

    # ── 27. purchase_credit_notes ──
    op.create_table('purchase_credit_notes',
        sa.Column('id', sa.UUID(), nullable=False, server_default=sa.text('gen_random_uuid()')),
        sa.Column('tenant_id', sa.UUID(), nullable=False),
        sa.Column('supplier_id', sa.UUID(), nullable=False),
        sa.Column('purchase_order_id', sa.UUID()),
        sa.Column('created_by', sa.UUID(), nullable=False),
        sa.Column('note_number', sa.String(30), nullable=False),
        sa.Column('reason', sa.String(255), nullable=False),
        sa.Column('subtotal', sa.Numeric(18, 2), nullable=False),
        sa.Column('tax_amount', sa.Numeric(18, 2), server_default='0'),
        sa.Column('total_amount', sa.Numeric(18, 2), nullable=False),
        sa.Column('status', sa.String(20), server_default='active'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()')),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id']),
        sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id']),
        sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id']),
        sa.ForeignKeyConstraint(['created_by'], ['users.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('tenant_id', 'note_number', name='uq_pcn_tenant_number'),
    )
    op.create_index('ix_pcn_tenant_supplier', 'purchase_credit_notes', ['tenant_id', 'supplier_id'])

    # ── 28. purchase_credit_note_items ──
    op.create_table('purchase_credit_note_items',
        sa.Column('id', sa.UUID(), nullable=False, server_default=sa.text('gen_random_uuid()')),
        sa.Column('credit_note_id', sa.UUID(), nullable=False),
        sa.Column('product_id', sa.UUID(), nullable=False),
        sa.Column('product_name', sa.String(255), nullable=False),
        sa.Column('quantity', sa.Numeric(12, 4), nullable=False),
        sa.Column('unit_cost', sa.Numeric(18, 2), nullable=False),
        sa.Column('tax_rate', sa.Numeric(8, 4), server_default='19.0'),
        sa.Column('subtotal', sa.Numeric(18, 2), nullable=False),
        sa.Column('tax_amount', sa.Numeric(18, 2), nullable=False),
        sa.Column('total', sa.Numeric(18, 2), nullable=False),
        sa.ForeignKeyConstraint(['credit_note_id'], ['purchase_credit_notes.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['product_id'], ['products.id']),
        sa.PrimaryKeyConstraint('id'),
    )

    # ── 29. purchase_debit_notes ──
    op.create_table('purchase_debit_notes',
        sa.Column('id', sa.UUID(), nullable=False, server_default=sa.text('gen_random_uuid()')),
        sa.Column('tenant_id', sa.UUID(), nullable=False),
        sa.Column('supplier_id', sa.UUID(), nullable=False),
        sa.Column('purchase_order_id', sa.UUID()),
        sa.Column('created_by', sa.UUID(), nullable=False),
        sa.Column('note_number', sa.String(30), nullable=False),
        sa.Column('reason', sa.String(255), nullable=False),
        sa.Column('amount', sa.Numeric(18, 2), nullable=False),
        sa.Column('tax_amount', sa.Numeric(18, 2), server_default='0'),
        sa.Column('total_amount', sa.Numeric(18, 2), nullable=False),
        sa.Column('status', sa.String(20), server_default='active'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()')),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id']),
        sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id']),
        sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id']),
        sa.ForeignKeyConstraint(['created_by'], ['users.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('tenant_id', 'note_number', name='uq_pdn_tenant_number'),
        sa.CheckConstraint('amount > 0', name='ck_pdn_amount'),
    )

    # ── 30. electronic_invoices ──
    op.create_table('electronic_invoices',
        sa.Column('id', sa.UUID(), nullable=False, server_default=sa.text('gen_random_uuid()')),
        sa.Column('tenant_id', sa.UUID(), nullable=False),
        sa.Column('sale_id', sa.UUID()),
        sa.Column('credit_note_id', sa.UUID()),
        sa.Column('created_by', sa.UUID(), nullable=False),
        sa.Column('document_type', sa.String(5), server_default='01'),
        sa.Column('invoice_number', sa.String(30), nullable=False),
        sa.Column('prefix', sa.String(10)),
        sa.Column('cufe', sa.String(200)),
        sa.Column('qr_code_url', sa.Text()),
        sa.Column('xml_url', sa.Text()),
        sa.Column('pdf_url', sa.Text()),
        sa.Column('status', sa.String(20), server_default='draft'),
        sa.Column('pta_provider', sa.String(50)),
        sa.Column('pta_request_id', sa.String(100)),
        sa.Column('pta_response', sa.Text()),
        sa.Column('dian_response_code', sa.String(10)),
        sa.Column('subtotal', sa.Numeric(18, 2), nullable=False),
        sa.Column('tax_amount', sa.Numeric(18, 2), nullable=False),
        sa.Column('total_amount', sa.Numeric(18, 2), nullable=False),
        sa.Column('customer_name', sa.String(255)),
        sa.Column('customer_tax_id', sa.String(20)),
        sa.Column('customer_email', sa.String(255)),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()')),
        sa.Column('sent_at', sa.DateTime(timezone=True)),
        sa.Column('accepted_at', sa.DateTime(timezone=True)),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id']),
        sa.ForeignKeyConstraint(['sale_id'], ['sales.id']),
        sa.ForeignKeyConstraint(['credit_note_id'], ['credit_notes.id']),
        sa.ForeignKeyConstraint(['created_by'], ['users.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('tenant_id', 'invoice_number', name='uq_ei_tenant_number'),
    )
    op.create_index('ix_ei_sale', 'electronic_invoices', ['sale_id'])
    op.create_index('ix_ei_tenant_status', 'electronic_invoices', ['tenant_id', 'status'])

    # ── 31. expenses ──
    op.create_table('expenses',
        sa.Column('id', sa.UUID(), nullable=False, server_default=sa.text('gen_random_uuid()')),
        sa.Column('tenant_id', sa.UUID(), nullable=False),
        sa.Column('created_by', sa.UUID(), nullable=False),
        sa.Column('expense_number', sa.String(30), nullable=False),
        sa.Column('expense_date', sa.DateTime(timezone=True), server_default=sa.text('now()')),
        sa.Column('puc_code', sa.String(10), nullable=False),
        sa.Column('concept', sa.String(255), nullable=False),
        sa.Column('amount', sa.Numeric(18, 2), nullable=False),
        sa.Column('tax_amount', sa.Numeric(18, 2), server_default='0'),
        sa.Column('total_amount', sa.Numeric(18, 2), nullable=False),
        sa.Column('supplier_id', sa.UUID()),
        sa.Column('payment_status', sa.String(20), server_default='paid'),
        sa.Column('payment_method', sa.String(30)),
        sa.Column('receipt_reference', sa.String(100)),
        sa.Column('notes', sa.Text()),
        sa.Column('status', sa.String(20), server_default='active'),
        sa.Column('paid_at', sa.DateTime(timezone=True)),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()')),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id']),
        sa.ForeignKeyConstraint(['created_by'], ['users.id']),
        sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('tenant_id', 'expense_number', name='uq_exp_tenant_number'),
        sa.CheckConstraint('amount > 0', name='ck_exp_amount'),
        sa.CheckConstraint("payment_status IN ('paid','pending')", name='ck_exp_pay_status'),
        sa.CheckConstraint("status IN ('active','voided')", name='ck_exp_status'),
    )
    op.create_index('ix_exp_tenant_date', 'expenses', ['tenant_id', 'expense_date'])

    # ── 32. withholding_configs ──
    op.create_table('withholding_configs',
        sa.Column('id', sa.UUID(), nullable=False, server_default=sa.text('gen_random_uuid()')),
        sa.Column('tenant_id', sa.UUID(), nullable=False),
        sa.Column('type', sa.String(20), nullable=False),
        sa.Column('name', sa.String(100), nullable=False),
        sa.Column('rate', sa.Numeric(8, 4), nullable=False),
        sa.Column('base_uvt', sa.Numeric(18, 2), server_default='0'),
        sa.Column('puc_code', sa.String(10), nullable=False),
        sa.Column('applies_to', sa.String(20), server_default='purchases'),
        sa.Column('is_active', sa.Boolean(), server_default='true'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()')),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.CheckConstraint("type IN ('retefuente','reteica','reteiva')", name='ck_wc_type'),
        sa.CheckConstraint('rate > 0 AND rate <= 100', name='ck_wc_rate'),
        sa.CheckConstraint("applies_to IN ('purchases','sales','both')", name='ck_wc_applies'),
    )

    # ── 33. journal_entries ──
    op.create_table('journal_entries',
        sa.Column('id', sa.UUID(), nullable=False, server_default=sa.text('gen_random_uuid()')),
        sa.Column('tenant_id', sa.UUID(), nullable=False),
        sa.Column('period_id', sa.UUID(), nullable=False),
        sa.Column('created_by', sa.UUID(), nullable=False),
        sa.Column('entry_date', sa.DateTime(timezone=True), server_default=sa.text('now()')),
        sa.Column('entry_type', sa.String(30), nullable=False),
        sa.Column('description', sa.String(500), nullable=False),
        sa.Column('source_document_type', sa.String(50)),
        sa.Column('source_document_id', sa.UUID()),
        sa.Column('is_reversed', sa.Boolean(), server_default='false'),
        sa.Column('reversal_of_id', sa.UUID()),
        sa.Column('total_debit', sa.Numeric(18, 2), server_default='0'),
        sa.Column('total_credit', sa.Numeric(18, 2), server_default='0'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()')),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id']),
        sa.ForeignKeyConstraint(['period_id'], ['accounting_periods.id']),
        sa.ForeignKeyConstraint(['created_by'], ['users.id']),
        sa.ForeignKeyConstraint(['reversal_of_id'], ['journal_entries.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.CheckConstraint(
            "entry_type IN ('SALE','SALE_COST','PURCHASE','PAYMENT','ADJUSTMENT','REVERSAL',"
            "'MANUAL','CLOSING','CASH_RECEIPT','CASH_DISBURSEMENT','TRANSFER','EXPENSE',"
            "'SUPPLIER_PAYMENT','CREDIT_NOTE_PURCHASE','DEBIT_NOTE','SALES_DEBIT_NOTE')",
            name='ck_je_type'
        ),
    )
    op.create_index('ix_je_tenant_date', 'journal_entries', ['tenant_id', 'entry_date'])
    op.create_index('ix_je_source', 'journal_entries', ['source_document_type', 'source_document_id'])

    # ── 34. journal_lines ──
    op.create_table('journal_lines',
        sa.Column('id', sa.UUID(), nullable=False, server_default=sa.text('gen_random_uuid()')),
        sa.Column('entry_id', sa.UUID(), nullable=False),
        sa.Column('account_id', sa.UUID(), nullable=False),
        sa.Column('debit_amount', sa.Numeric(18, 2), server_default='0'),
        sa.Column('credit_amount', sa.Numeric(18, 2), server_default='0'),
        sa.Column('description', sa.String(255)),
        sa.ForeignKeyConstraint(['entry_id'], ['journal_entries.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['account_id'], ['chart_of_accounts.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.CheckConstraint('debit_amount >= 0', name='ck_jl_debit'),
        sa.CheckConstraint('credit_amount >= 0', name='ck_jl_credit'),
    )
    op.create_index('ix_jl_account', 'journal_lines', ['account_id'])

    # ── 35. stock_movements ──
    op.create_table('stock_movements',
        sa.Column('id', sa.UUID(), nullable=False, server_default=sa.text('gen_random_uuid()')),
        sa.Column('tenant_id', sa.UUID(), nullable=False),
        sa.Column('product_id', sa.UUID(), nullable=False),
        sa.Column('created_by', sa.UUID(), nullable=False),
        sa.Column('movement_type', sa.String(30), nullable=False),
        sa.Column('quantity', sa.Numeric(12, 4), nullable=False),
        sa.Column('stock_before', sa.Numeric(12, 4), nullable=False),
        sa.Column('stock_after', sa.Numeric(12, 4), nullable=False),
        sa.Column('unit_cost', sa.Numeric(18, 6), server_default='0'),
        sa.Column('reference_type', sa.String(50)),
        sa.Column('reference_id', sa.UUID()),
        sa.Column('reason', sa.String(255)),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()')),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id']),
        sa.ForeignKeyConstraint(['product_id'], ['products.id']),
        sa.ForeignKeyConstraint(['created_by'], ['users.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.CheckConstraint(
            "movement_type IN ('initial_stock','sale','purchase_receipt','adjustment_positive',"
            "'adjustment_negative','return_sale','return_purchase','transfer_in','transfer_out')",
            name='ck_sm_type'
        ),
    )
    op.create_index('ix_sm_tenant_product_date', 'stock_movements', ['tenant_id', 'product_id', 'created_at'])
    op.create_index('ix_sm_reference', 'stock_movements', ['reference_type', 'reference_id'])

    # ── 36. inventory_adjustments ──
    op.create_table('inventory_adjustments',
        sa.Column('id', sa.UUID(), nullable=False, server_default=sa.text('gen_random_uuid()')),
        sa.Column('tenant_id', sa.UUID(), nullable=False),
        sa.Column('created_by', sa.UUID(), nullable=False),
        sa.Column('approved_by', sa.UUID()),
        sa.Column('adjustment_number', sa.String(30), nullable=False),
        sa.Column('adjustment_type', sa.String(20), server_default='physical_count'),
        sa.Column('status', sa.String(20), server_default='draft'),
        sa.Column('notes', sa.Text()),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()')),
        sa.Column('approved_at', sa.DateTime(timezone=True)),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id']),
        sa.ForeignKeyConstraint(['created_by'], ['users.id']),
        sa.ForeignKeyConstraint(['approved_by'], ['users.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('tenant_id', 'adjustment_number', name='uq_ia_tenant_number'),
        sa.CheckConstraint("adjustment_type IN ('physical_count','damage','loss','donation')", name='ck_ia_type'),
        sa.CheckConstraint("status IN ('draft','pending_approval','approved','rejected')", name='ck_ia_status'),
    )

    # ── 37. inventory_adjustment_items ──
    op.create_table('inventory_adjustment_items',
        sa.Column('id', sa.UUID(), nullable=False, server_default=sa.text('gen_random_uuid()')),
        sa.Column('adjustment_id', sa.UUID(), nullable=False),
        sa.Column('product_id', sa.UUID(), nullable=False),
        sa.Column('product_name', sa.String(255), nullable=False),
        sa.Column('stock_system', sa.Numeric(12, 4), nullable=False),
        sa.Column('stock_counted', sa.Numeric(12, 4), nullable=False),
        sa.Column('difference', sa.Numeric(12, 4), nullable=False),
        sa.Column('unit_cost', sa.Numeric(18, 6), nullable=False),
        sa.Column('total_cost', sa.Numeric(18, 2), nullable=False),
        sa.ForeignKeyConstraint(['adjustment_id'], ['inventory_adjustments.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['product_id'], ['products.id']),
        sa.PrimaryKeyConstraint('id'),
    )

    # ── 38. discount_policies ──
    op.create_table('discount_policies',
        sa.Column('id', sa.UUID(), nullable=False, server_default=sa.text('gen_random_uuid()')),
        sa.Column('tenant_id', sa.UUID(), nullable=False),
        sa.Column('role_id', sa.UUID(), nullable=False),
        sa.Column('max_discount_pct', sa.Numeric(8, 4), server_default='0'),
        sa.Column('requires_approval_above', sa.Numeric(8, 4)),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()')),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id']),
        sa.ForeignKeyConstraint(['role_id'], ['roles.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('tenant_id', 'role_id', name='uq_dp_tenant_role'),
        sa.CheckConstraint('max_discount_pct >= 0 AND max_discount_pct <= 100', name='ck_dp_pct'),
    )

    # ── 39. cash_receipts ──
    op.create_table('cash_receipts',
        sa.Column('id', sa.UUID(), nullable=False, server_default=sa.text('gen_random_uuid()')),
        sa.Column('tenant_id', sa.UUID(), nullable=False),
        sa.Column('cash_session_id', sa.UUID()),
        sa.Column('created_by', sa.UUID(), nullable=False),
        sa.Column('receipt_number', sa.String(30), nullable=False),
        sa.Column('receipt_date', sa.DateTime(timezone=True), server_default=sa.text('now()')),
        sa.Column('source_type', sa.String(30), nullable=False),
        sa.Column('source_id', sa.UUID()),
        sa.Column('source_name', sa.String(255)),
        sa.Column('concept', sa.String(255), nullable=False),
        sa.Column('amount', sa.Numeric(18, 2), nullable=False),
        sa.Column('payment_method', sa.String(30), server_default='cash'),
        sa.Column('reference', sa.String(100)),
        sa.Column('notes', sa.Text()),
        sa.Column('status', sa.String(20), server_default='active'),
        sa.Column('voided_at', sa.DateTime(timezone=True)),
        sa.Column('voided_by', sa.UUID()),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()')),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id']),
        sa.ForeignKeyConstraint(['cash_session_id'], ['cash_sessions.id']),
        sa.ForeignKeyConstraint(['created_by'], ['users.id']),
        sa.ForeignKeyConstraint(['voided_by'], ['users.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('tenant_id', 'receipt_number', name='uq_cr_tenant_number'),
        sa.CheckConstraint("source_type IN ('customer_payment','other_income','loan','partner_capital')", name='ck_cr_source'),
        sa.CheckConstraint('amount > 0', name='ck_cr_amount'),
        sa.CheckConstraint("status IN ('active','voided')", name='ck_cr_status'),
        sa.CheckConstraint("payment_method IN ('cash','transfer','check','nequi','daviplata')", name='ck_cr_method'),
    )
    op.create_index('ix_cr_tenant_date', 'cash_receipts', ['tenant_id', 'receipt_date'])

    # ── 40. cash_disbursements ──
    op.create_table('cash_disbursements',
        sa.Column('id', sa.UUID(), nullable=False, server_default=sa.text('gen_random_uuid()')),
        sa.Column('tenant_id', sa.UUID(), nullable=False),
        sa.Column('cash_session_id', sa.UUID()),
        sa.Column('created_by', sa.UUID(), nullable=False),
        sa.Column('disbursement_number', sa.String(30), nullable=False),
        sa.Column('disbursement_date', sa.DateTime(timezone=True), server_default=sa.text('now()')),
        sa.Column('destination_type', sa.String(30), nullable=False),
        sa.Column('destination_id', sa.UUID()),
        sa.Column('destination_name', sa.String(255)),
        sa.Column('concept', sa.String(255), nullable=False),
        sa.Column('amount', sa.Numeric(18, 2), nullable=False),
        sa.Column('payment_method', sa.String(30), server_default='cash'),
        sa.Column('reference', sa.String(100)),
        sa.Column('notes', sa.Text()),
        sa.Column('puc_code', sa.String(10)),
        sa.Column('approved_by', sa.UUID()),
        sa.Column('approved_at', sa.DateTime(timezone=True)),
        sa.Column('status', sa.String(20), server_default='active'),
        sa.Column('voided_at', sa.DateTime(timezone=True)),
        sa.Column('voided_by', sa.UUID()),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()')),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id']),
        sa.ForeignKeyConstraint(['cash_session_id'], ['cash_sessions.id']),
        sa.ForeignKeyConstraint(['created_by'], ['users.id']),
        sa.ForeignKeyConstraint(['approved_by'], ['users.id']),
        sa.ForeignKeyConstraint(['voided_by'], ['users.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('tenant_id', 'disbursement_number', name='uq_cd_tenant_number'),
        sa.CheckConstraint("destination_type IN ('supplier_payment','expense','petty_cash','bank_transfer','other')", name='ck_cd_dest'),
        sa.CheckConstraint('amount > 0', name='ck_cd_amount'),
        sa.CheckConstraint("status IN ('active','voided')", name='ck_cd_status'),
        sa.CheckConstraint("payment_method IN ('cash','transfer','check','nequi','daviplata')", name='ck_cd_method'),
    )
    op.create_index('ix_cd_tenant_date', 'cash_disbursements', ['tenant_id', 'disbursement_date'])

    # ── 41. cash_transfers ──
    op.create_table('cash_transfers',
        sa.Column('id', sa.UUID(), nullable=False, server_default=sa.text('gen_random_uuid()')),
        sa.Column('tenant_id', sa.UUID(), nullable=False),
        sa.Column('created_by', sa.UUID(), nullable=False),
        sa.Column('transfer_number', sa.String(30), nullable=False),
        sa.Column('transfer_date', sa.DateTime(timezone=True), server_default=sa.text('now()')),
        sa.Column('from_account_puc', sa.String(10), nullable=False),
        sa.Column('to_account_puc', sa.String(10), nullable=False),
        sa.Column('amount', sa.Numeric(18, 2), nullable=False),
        sa.Column('reference', sa.String(100)),
        sa.Column('notes', sa.Text()),
        sa.Column('status', sa.String(20), server_default='completed'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()')),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id']),
        sa.ForeignKeyConstraint(['created_by'], ['users.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('tenant_id', 'transfer_number', name='uq_ct_tenant_number'),
        sa.CheckConstraint('amount > 0', name='ck_ct_amount'),
        sa.CheckConstraint("status IN ('completed','voided')", name='ck_ct_status'),
    )

    # ── 42. cash_count_details ──
    op.create_table('cash_count_details',
        sa.Column('id', sa.UUID(), nullable=False, server_default=sa.text('gen_random_uuid()')),
        sa.Column('cash_session_id', sa.UUID(), nullable=False),
        sa.Column('denomination', sa.Integer(), nullable=False),
        sa.Column('quantity', sa.Integer(), server_default='0'),
        sa.Column('subtotal', sa.Numeric(18, 2), nullable=False),
        sa.ForeignKeyConstraint(['cash_session_id'], ['cash_sessions.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.CheckConstraint('denomination > 0', name='ck_ccd_denom'),
        sa.CheckConstraint('quantity >= 0', name='ck_ccd_qty'),
    )

    # ── 43. audit_logs ──
    op.create_table('audit_logs',
        sa.Column('id', sa.UUID(), nullable=False, server_default=sa.text('gen_random_uuid()')),
        sa.Column('tenant_id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID()),
        sa.Column('action', sa.String(50), nullable=False),
        sa.Column('entity_type', sa.String(50), nullable=False),
        sa.Column('entity_id', sa.UUID(), nullable=False),
        sa.Column('changes', postgresql.JSONB(astext_type=sa.Text())),
        sa.Column('ip_address', sa.String(45)),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()')),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id']),
        sa.ForeignKeyConstraint(['user_id'], ['users.id']),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('idx_audit_tenant_date', 'audit_logs', ['tenant_id', 'created_at'])
    op.create_index('idx_audit_tenant_entity', 'audit_logs', ['tenant_id', 'entity_type', 'entity_id'])
    op.create_index('ix_audit_logs_tenant_id', 'audit_logs', ['tenant_id'])


def downgrade():
    tables = [
        'audit_logs', 'cash_count_details', 'cash_transfers', 'cash_disbursements',
        'cash_receipts', 'discount_policies', 'inventory_adjustment_items',
        'inventory_adjustments', 'stock_movements', 'journal_lines', 'journal_entries',
        'withholding_configs', 'expenses', 'electronic_invoices', 'purchase_debit_notes',
        'purchase_credit_note_items', 'purchase_credit_notes', 'supplier_payments',
        'purchase_order_items', 'purchase_orders', 'collection_campaign_items',
        'collection_campaigns', 'sales_debit_notes', 'customer_payments',
        'credit_note_items', 'credit_notes', 'payments', 'sale_items', 'sales',
        'cash_sessions', 'chart_of_accounts', 'accounting_periods', 'products',
        'categories', 'customers', 'suppliers', 'refresh_tokens', 'user_roles',
        'role_permissions', 'roles', 'users', 'permissions', 'tenants',
    ]
    for t in tables:
        op.drop_table(t)
