"""add collection campaigns

Revision ID: 22bbbcb0f17c
Revises: 5dfc9a5d8774
Create Date: 2026-03-25 18:33:38.985095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22bbbcb0f17c'
down_revision = '5dfc9a5d8774'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection_campaigns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('campaign_number', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('target_type', sa.String(length=30), nullable=False),
    sa.Column('min_days_overdue', sa.Integer(), nullable=False),
    sa.Column('min_amount_due', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('message_template', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('scheduled_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_customers', sa.Integer(), nullable=False),
    sa.Column('total_amount_targeted', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'active', 'completed', 'cancelled')", name='ck_cc_status'),
    sa.CheckConstraint("target_type IN ('all_overdue', 'by_age', 'by_amount', 'specific_customers')", name='ck_cc_target'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'campaign_number', name='uq_cc_tenant_number')
    )
    op.create_table('collection_campaign_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('sale_id', sa.UUID(), nullable=True),
    sa.Column('amount_due', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('days_overdue', sa.Integer(), nullable=False),
    sa.Column('contact_method', sa.String(length=20), nullable=True),
    sa.Column('contact_status', sa.String(length=20), nullable=False),
    sa.Column('contact_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('promise_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.CheckConstraint("contact_method IN ('sms', 'whatsapp', 'email', 'phone_call')", name='ck_cci_method'),
    sa.CheckConstraint("contact_status IN ('pending', 'contacted', 'promised', 'paid', 'failed')", name='ck_cci_status'),
    sa.ForeignKeyConstraint(['campaign_id'], ['collection_campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('collection_campaign_items')
    op.drop_table('collection_campaigns')
    # ### end Alembic commands ###
