"""add cash module tables

Revision ID: 2ef3a5d681a2
Revises: 28dcde9b0fb6
Create Date: 2026-03-25 15:17:50.941598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ef3a5d681a2'
down_revision = '28dcde9b0fb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cash_transfers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('transfer_number', sa.String(length=30), nullable=False),
    sa.Column('transfer_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('from_account_puc', sa.String(length=10), nullable=False),
    sa.Column('to_account_puc', sa.String(length=10), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('completed', 'voided')", name='ck_ct_status'),
    sa.CheckConstraint('amount > 0', name='ck_ct_amount'),
    sa.CheckConstraint('from_account_puc != to_account_puc', name='ck_ct_diff_accounts'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'transfer_number', name='uq_ct_tenant_number')
    )
    op.create_table('cash_count_details',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cash_session_id', sa.UUID(), nullable=False),
    sa.Column('denomination', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.CheckConstraint('denomination > 0', name='ck_ccd_denomination'),
    sa.CheckConstraint('quantity >= 0', name='ck_ccd_quantity'),
    sa.ForeignKeyConstraint(['cash_session_id'], ['cash_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cash_disbursements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('cash_session_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('disbursement_number', sa.String(length=30), nullable=False),
    sa.Column('disbursement_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('destination_type', sa.String(length=30), nullable=False),
    sa.Column('destination_id', sa.UUID(), nullable=True),
    sa.Column('destination_name', sa.String(length=255), nullable=True),
    sa.Column('concept', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=30), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('puc_code', sa.String(length=10), nullable=True),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('voided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('voided_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("destination_type IN ('supplier_payment', 'expense', 'petty_cash', 'bank_transfer', 'other')", name='ck_cd_dest_type'),
    sa.CheckConstraint("payment_method IN ('cash', 'transfer', 'check', 'nequi', 'daviplata')", name='ck_cd_method'),
    sa.CheckConstraint("status IN ('active', 'voided')", name='ck_cd_status'),
    sa.CheckConstraint('amount > 0', name='ck_cd_amount'),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['cash_session_id'], ['cash_sessions.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['voided_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'disbursement_number', name='uq_cd_tenant_number')
    )
    with op.batch_alter_table('cash_disbursements', schema=None) as batch_op:
        batch_op.create_index('idx_cd_tenant_date', ['tenant_id', 'disbursement_date'], unique=False)

    op.create_table('cash_receipts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('cash_session_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('receipt_number', sa.String(length=30), nullable=False),
    sa.Column('receipt_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_type', sa.String(length=30), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('source_name', sa.String(length=255), nullable=True),
    sa.Column('concept', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=30), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('voided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('voided_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("payment_method IN ('cash', 'transfer', 'check', 'nequi', 'daviplata')", name='ck_cr_method'),
    sa.CheckConstraint("source_type IN ('customer_payment', 'other_income', 'loan', 'partner_capital')", name='ck_cr_source_type'),
    sa.CheckConstraint("status IN ('active', 'voided')", name='ck_cr_status'),
    sa.CheckConstraint('amount > 0', name='ck_cr_amount'),
    sa.ForeignKeyConstraint(['cash_session_id'], ['cash_sessions.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['voided_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'receipt_number', name='uq_cr_tenant_number')
    )
    with op.batch_alter_table('cash_receipts', schema=None) as batch_op:
        batch_op.create_index('idx_cr_tenant_date', ['tenant_id', 'receipt_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cash_receipts', schema=None) as batch_op:
        batch_op.drop_index('idx_cr_tenant_date')

    op.drop_table('cash_receipts')
    with op.batch_alter_table('cash_disbursements', schema=None) as batch_op:
        batch_op.drop_index('idx_cd_tenant_date')

    op.drop_table('cash_disbursements')
    op.drop_table('cash_count_details')
    op.drop_table('cash_transfers')
    # ### end Alembic commands ###
