"""add smtp fields to tenant

Revision ID: 2f69b930a117
Revises: 863b1a90c599
Create Date: 2026-03-26 19:55:06.629873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f69b930a117'
down_revision = '863b1a90c599'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('smtp_host', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('smtp_port', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('smtp_user', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('smtp_password', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('smtp_from_email', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_column('smtp_from_email')
        batch_op.drop_column('smtp_password')
        batch_op.drop_column('smtp_user')
        batch_op.drop_column('smtp_port')
        batch_op.drop_column('smtp_host')

    # ### end Alembic commands ###
