"""add document_type credit_note_id to electronic_invoices

Revision ID: 5dfc9a5d8774
Revises: ab61e88f523e
Create Date: 2026-03-25 17:23:47.820006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dfc9a5d8774'
down_revision = 'ab61e88f523e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('electronic_invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('credit_note_id', sa.UUID(), nullable=True))
        batch_op.add_column(sa.Column('document_type', sa.String(length=5), nullable=False, server_default='01'))
        batch_op.alter_column('sale_id',
               existing_type=sa.UUID(),
               nullable=True)
        batch_op.create_foreign_key(None, 'credit_notes', ['credit_note_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('electronic_invoices', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('sale_id',
               existing_type=sa.UUID(),
               nullable=False)
        batch_op.drop_column('document_type')
        batch_op.drop_column('credit_note_id')

    # ### end Alembic commands ###
