"""add rendered_message to campaign_items

Revision ID: 863b1a90c599
Revises: 22bbbcb0f17c
Create Date: 2026-03-25 19:12:31.353159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '863b1a90c599'
down_revision = '22bbbcb0f17c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collection_campaign_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rendered_message', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collection_campaign_items', schema=None) as batch_op:
        batch_op.drop_column('rendered_message')

    # ### end Alembic commands ###
