"""add expenses withholding_configs

Revision ID: ab61e88f523e
Revises: d796c3ab511f
Create Date: 2026-03-25 15:30:54.183187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab61e88f523e'
down_revision = 'd796c3ab511f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('withholding_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('rate', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('base_uvt', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('puc_code', sa.String(length=10), nullable=False),
    sa.Column('applies_to', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("applies_to IN ('purchases', 'sales', 'both')", name='ck_wc_applies'),
    sa.CheckConstraint("type IN ('retefuente', 'reteica', 'reteiva')", name='ck_wc_type'),
    sa.CheckConstraint('rate > 0 AND rate <= 100', name='ck_wc_rate'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('expenses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('expense_number', sa.String(length=30), nullable=False),
    sa.Column('expense_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('puc_code', sa.String(length=10), nullable=False),
    sa.Column('concept', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=True),
    sa.Column('payment_status', sa.String(length=20), nullable=False),
    sa.Column('payment_method', sa.String(length=30), nullable=True),
    sa.Column('receipt_reference', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("payment_status IN ('paid', 'pending')", name='ck_exp_pay_status'),
    sa.CheckConstraint("status IN ('active', 'voided')", name='ck_exp_status'),
    sa.CheckConstraint('amount > 0', name='ck_exp_amount'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'expense_number', name='uq_exp_tenant_number')
    )
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.create_index('idx_exp_tenant_date', ['tenant_id', 'expense_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_index('idx_exp_tenant_date')

    op.drop_table('expenses')
    op.drop_table('withholding_configs')
    # ### end Alembic commands ###
