"""add inventory_adjustments discount_policies

Revision ID: d796c3ab511f
Revises: f04f7d011a0a
Create Date: 2026-03-25 15:27:58.217887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd796c3ab511f'
down_revision = 'f04f7d011a0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discount_policies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('max_discount_pct', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('requires_approval_above', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('max_discount_pct >= 0 AND max_discount_pct <= 100', name='ck_dp_max'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'role_id', name='uq_dp_tenant_role')
    )
    op.create_table('inventory_adjustments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('adjustment_number', sa.String(length=30), nullable=False),
    sa.Column('adjustment_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("adjustment_type IN ('physical_count', 'damage', 'loss', 'donation')", name='ck_ia_type'),
    sa.CheckConstraint("status IN ('draft', 'pending_approval', 'approved', 'rejected')", name='ck_ia_status'),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'adjustment_number', name='uq_ia_tenant_number')
    )
    op.create_table('inventory_adjustment_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('adjustment_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('stock_system', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('stock_counted', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('difference', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['adjustment_id'], ['inventory_adjustments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventory_adjustment_items')
    op.drop_table('inventory_adjustments')
    op.drop_table('discount_policies')
    # ### end Alembic commands ###
