"""add CxC sales credit customer_payments sales_debit_notes

Revision ID: f04f7d011a0a
Revises: 2ef3a5d681a2
Create Date: 2026-03-25 15:23:21.192860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f04f7d011a0a'
down_revision = '2ef3a5d681a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('sale_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('payment_number', sa.String(length=30), nullable=False),
    sa.Column('payment_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=30), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('completed', 'voided')", name='ck_cp_status'),
    sa.CheckConstraint('amount > 0', name='ck_cp_amount'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'payment_number', name='uq_cp_tenant_number')
    )
    with op.batch_alter_table('customer_payments', schema=None) as batch_op:
        batch_op.create_index('idx_cp_tenant_customer', ['tenant_id', 'customer_id'], unique=False)

    op.create_table('sales_debit_notes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('sale_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('note_number', sa.String(length=30), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_sdn_amount'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'note_number', name='uq_sdn_tenant_number')
    )
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_id', sa.UUID(), nullable=True))
        batch_op.add_column(sa.Column('sale_type', sa.String(length=20), nullable=False, server_default='cash'))
        batch_op.add_column(sa.Column('credit_days', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('due_date', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('payment_status', sa.String(length=20), nullable=False, server_default='paid'))
        batch_op.add_column(sa.Column('amount_paid', sa.Numeric(precision=18, scale=2), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('amount_due', sa.Numeric(precision=18, scale=2), nullable=False, server_default='0'))
        batch_op.create_foreign_key(None, 'customers', ['customer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('amount_due')
        batch_op.drop_column('amount_paid')
        batch_op.drop_column('payment_status')
        batch_op.drop_column('due_date')
        batch_op.drop_column('credit_days')
        batch_op.drop_column('sale_type')
        batch_op.drop_column('customer_id')

    op.drop_table('sales_debit_notes')
    with op.batch_alter_table('customer_payments', schema=None) as batch_op:
        batch_op.drop_index('idx_cp_tenant_customer')

    op.drop_table('customer_payments')
    # ### end Alembic commands ###
